# Generated by Django 5.1.7 on 2025-03-19 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_scheduledtask_delete_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledtask',
            name='activation_method',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
